apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment  # naming the deployment

spec:
  selector:
    matchLabels:
      app: nginx  # look for this label to match with k8s service
  
  # Let's create a replica set of this with 2 instances/pods
  replicas: 2
  
  # Template to use its label for k8s service to launch in the browser
  template:
    metadata:
      labels:
        app: nginx  # this label onnects to the service or any other
    spec:
      containers:
      - name: nginx
        image: am93596/sre_customised_nginx:latest
        ports:
        - containerPort: 80
