apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-db-pv
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: /data/db
    type: Directory